AppBundle\Entity\Search:
    type:  entity
    repositoryClass: AppBundle\Entity\SearchRepository
    table: search
    id:
        term:
            type: string
            length: 255
    fields:
      val:
        type: integer

    #oneToMany:
    #    term:
    #        targetEntity: AppBundle\Entity\UserSearch
    #        inversedBy: searchTerm