AppBundle\Entity\UserSearch:
    type:  entity
    repositoryClass: AppBundle\Entity\UserSearchRepository
    table: user_search
    id:
        searchTerm:
            type: string
            length: 255
            associationKey: true
        userId:
            type: integer
            associationKey: true

    fields:
      track:
        type: boolean

    manyToOne:
      userId:
          targetEntity: AppBundle\Entity\User
          #joinColum:
          #  name: user_id
          # referencedColumnName: id
      searchTerm:
          targetEntity: AppBundle\Entity\Search
          joinColumn:
            #name: search_term
            referencedColumnName: term

